version: '3'
services:
  db:
    container_name: caseone_db_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    image: postgres:9.6
    hostname: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    stdin_open: true
    tty: true
    container_name: app_container
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/casaone_assignment
    ports:
      - "3000:3000"
    depends_on:
      - db
